### ISSUE TITLE
Invalid JSON response from server

### ISSUE THREAD

**Issue by sapkal-manish** [jiem/sendgrid-mustache#1]
I am getting error "Invalid JSON response from server" in callback. but email(s) is delivered successfully. I don't understand, why it is throwing error? and How to track that Emails status. like each email is delivered, bounced, spammed, clicked etc...

thanks

**Comment by jiem** [comment]
The callback arguments (success, message) are generated by Sendgrid, I can't have more info about the error. To track the mails analytics, you can check them in your Sendgrid dashboard. Cheers
