### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by thebergamo** [jiem/sendgrid-mustache#4]
This project are living yet?

Maybe you can add some tests or need help to improve it?

**Comment by jiem** [comment]
Hi! I'm not developing this project very much but I'm still using it to send hundred of thousands of mails for my startup. Any help to improve it is appreciated :)

**Comment by thebergamo** [comment]
I'm trying to use it, but the dependencies are broken :/ for my proposes I  create this repo too inspired in this!
https://github.com/antonproject/sendgrid-mustacher
